backend:
  name: github
  repo: mainaccessdoor/mainaccessdoor.github.io
  branch: main
  base_url: https://sveltia-cms-auth.mainaccessdoor.workers.dev

# backend:
#   name: test-repo

logo:
  src: ../assets/logo.jpg
  show_in_header: true

app_title: mainaccessdoor

media_folder: /static/assets
public_folder: /assets

media_libraries:
  default:
    config:
      transformations:
        raster_image:
          format: webp
          quality: 85
          width: 1600
          height: 1600
        svg:
          optimize: true

collections:
  - name: works # Used in routes, e.g., /admin/collections/post
    label: Works # Used in the UI
    folder: /content/works # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    media_folder: "{{media_folder}}/works/{{slug}}"
    public_folder: "{{public_folder}}/works/{{slug}}"
    fields:
      - name: title
        label: 제목
        required: true

      - name: date
        label: 날짜
        widget: datetime
        type: date
        required: true

      - name: medium
        label: 제작방식 및 재료
        required: false

      - name: dimensions
        label: 크기
        required: false

      - name: pages
        label: 페이지 수
        widget: number
        required: false

      - name: description_kr
        label: 설명 (국문)
        widget: text
        required: false

      - name: description_eng
        label: 설명 (영문)
        widget: text
        required: false

      - name: etc_kr
        label: 기타 (국문)
        required: false

      - name: etc_eng
        label: 기타 (영문)
        required: false

      - name: thumbnail
        label: 썸네일
        widget: file
        multiple: false
        required: false

      - name: images
        label: 이미지
        widget: file
        multiple: true
        required: true

  - name: metatag
    label: 메타태그
    files:
      - name: metatag
        label: 메타태그
        file: content/metatag.md
        fields:
          - label: 제목
            name: title
            widget: string
            required: true
            hint: "링크 제목"

          - label: 설명
            name: description
            widget: string
            required: true
            hint: "링크 설명"

          - label: 사진
            name: image
            widget: image
            required: false
            hint: "링크 미리보기 사진"

          - label: 파비콘
            name: favicon
            widget: image
            required: false
